Feat/target toggle component
unepwcmc/bip pull request #51
Opened 2022-11-14 17:16 UTC by nym1k

Target Toggle Component on homepage

- Updated structure of component to be more semantic
- Updated styles as per designs from Iman
- SDGs now use name as a label (shorter text e.g., Goal 1) and description as a title (longer text e.g., End poverty in all its forms everywhere.)

2022-11-16 16:15 UTC, WillKocur requested changes
Looking good! Some small comments below:

1. The Label and title (homepage-targets__title) are not always present. When either one isn’t there, could you remove the element - I think it’s pushing off alignment although hard to see with no images!
2. Can you add shadow around selected sdg as in designs
3. Home targets card description needs some styling on MEA tab at top of card - looks like maybe it just needs popping in p tags actually.
4. The main tabs (SDGs, MEAs, Themes, National Indicators) have a small gap in the breakpoints where they wrap onto two lines. Might be worth running by Iman to see if she wants to reduce the font/padding size at all to prevent that. Difficult with only two breakpoints… 
<img width="888" alt="Screenshot 2022-11-16 at 16 01 50" src="https://user-images.githubusercontent.com/39922722/202234271-67c1cbb0-8b6d-4169-b139-b2bc62673ff0.png">
5. On safari the homepage-targets__logo goes really wide, however this may be just an issue when the image doesn’t load. Did this happen for you:
<img width="888" alt="Screenshot 2022-11-16 at 16 04 11" src="https://user-images.githubusercontent.com/39922722/202234220-689d8ac6-8330-44b2-81a0-d14dbceb3e5b.png">


I popped some optional comments in the code - only if you have time, and seems like things are quite rushed, so happy for them to be left if you don't.

2022-11-17 11:37 UTC, nym1k commented on app/assets/stylesheets/components/browse.scss
> +      color: $prussian-blue;
Updated

2022-11-17 11:38 UTC, nym1k commented on app/assets/stylesheets/components/homepage-targets.scss
> +      border-radius: 100%;
Doesn't seem to be, i've deleted it

2022-11-17 11:41 UTC, nym1k commented on app/assets/stylesheets/components/targets-browse.scss
> +    margin: 0 0 vr(-2) vr(-2);
Updated to use a variable

2022-11-17 11:55 UTC, nym1k commented on app/assets/stylesheets/components/targets-browse.scss
> -        position: absolute;
Couldn't see the properties in the design, but have them now so added it.

2022-11-17 11:57 UTC, nym1k commented on app/assets/stylesheets/components/themes-browse.scss
>      padding: vr(1) vr(1.6666666);
This wasn't my code, but when I try that it seems to work so I will use it.

2022-11-17 11:57 UTC, nym1k commented on app/assets/stylesheets/components/themes-browse.scss
> +      object-fit: contain;
Yes, we no longer support IE11

2022-11-17 11:58 UTC, nym1k commented on app/assets/stylesheets/variables/typography.scss
> +    color: $black  ),
Fixed

2022-11-17 17:59 UTC, nym1k commented on app/assets/stylesheets/components/homepage-targets.scss
> -    font-family: Merriweather;
I have pulled them in and tried to utilise them were possible, I have had to modify them slightly to make reusing possible.

2022-11-17 18:00 UTC, nym1k commented
Hi @WillKocur, I have had to modify your mixins slightly to better adapt them for use in multiple places. I have also reworked how the link with arrow icon works and put this in to a button mixin.

2022-11-17 18:01 UTC, nym1k commented
Also, from your list I am not seeing number 5 in safari, perhaps this is because I have the images loaded?

2022-11-17 18:41 UTC, WillKocur commented
> Also, from your list I am not seeing number 5 in safari, perhaps this is because I have the images loaded?

Good good - I assume it's just when the image doesn't load then.

2022-11-17 18:46 UTC, WillKocur commented
@nym1k Happy with these changes - I think the mixins look good 👍  Just the one thing that is a little off after reworking the styles:

The button on the resources page is a little different (on the left and not an arrow, also has a different class on the icon). So the mixin doesn't quite work for this one (see padding for vertical alignment and padding).

Perhaps just a case of having different classes/mixins for the two button/link types...

![Screenshot 2022-11-17 at 18 42 49](https://user-images.githubusercontent.com/39922722/202531222-569be862-96f2-4459-a948-c56e31f889ef.png)

2022-11-18 11:03 UTC, nym1k commented
Reworked the search page results link element to allow for multiple types of link with icon

2022-11-18 11:51 UTC, merged