Feat/resource listing styled
unepwcmc/bip pull request #55
Opened 2022-11-15 15:14 UTC by WillKocur

https://unep-wcmc.codebasehq.com/projects/bip-website/tickets/9

- Refactor results cards templates using helper
- Style select
- Remove tags from results cards

2022-11-16 12:25 UTC, nym1k requested changes
Minor changes

2022-11-16 16:53 UTC, WillKocur commented on app/assets/stylesheets/components/select.scss
> +    @include font(select);
Moved - I've kept the appearance styling slightly separate as it's overwriting system styling, but have otherwise gone back to normal ordering :)

2022-11-16 17:02 UTC, WillKocur commented
@nym1k all done 👍

2022-11-17 14:46 UTC, nym1k approved these changes

2022-11-17 14:46 UTC, merged