feat: add filter styling for search and resources page
unepwcmc/bip pull request #58
Opened 2022-11-16 19:25 UTC by WillKocur

Adds styling to filters on search and resources page.

Note the filters on search are different and not in the designs so I've just touched them up to be more similar to the resources page.

https://unep-wcmc.codebasehq.com/projects/bip-website/tickets/8

2022-11-18 13:24 UTC, WillKocur commented
@nym1k Discussed changes made :)

2022-11-18 15:56 UTC, nym1k requested changes
Just some minor changes

Also, when you hover over a ticked filter, the tick itself seems to have an underline too
![Screenshot 2022-11-18 at 11 18 30](https://user-images.githubusercontent.com/16685504/202746848-bd57cfd8-816f-480e-8e99-c7df655e6234.png)

2022-11-18 15:56 UTC, nym1k commented on app/assets/stylesheets/components/filters.scss
> +    border: solid 2px $border--checkbox;
Should we change from px to rem?

2022-11-18 15:56 UTC, nym1k commented on app/assets/stylesheets/components/filters.scss
> +      border-width: 1px;
Should we change from px to rem?

2022-11-18 16:24 UTC, WillKocur commented on app/assets/stylesheets/components/filters.scss
> +    padding: vr(1) 0;
Ah yes, I think this was for the filters in the dropdown on search, but have removed padding and put margin on the dropdown trigger

2022-11-18 16:28 UTC, WillKocur commented
> Just some minor changes
> 
> Also, when you hover over a ticked filter, the tick itself seems to have an underline too ![Screenshot 2022-11-18 at 11 18 30](https://user-images.githubusercontent.com/16685504/202746848-bd57cfd8-816f-480e-8e99-c7df655e6234.png)

Fixed using link-reset, but can address this re your comment in the other PR if needed :)

2022-11-21 10:06 UTC, nym1k requested changes
One tiny change then ready to merge

2022-11-21 10:06 UTC, nym1k commented on app/assets/stylesheets/components/filters.scss
> +      border-width: 1px;
Not sure if the px here were missed for this border

2022-11-21 10:21 UTC, WillKocur commented
Ah missed that, yes! Done now @nym1k

2022-11-21 13:00 UTC, nym1k approved these changes

2022-11-21 13:00 UTC, merged